application: sec-coding-2014
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /js
  static_dir: ../client/js
- url: /bootstrap
  static_dir: ../client/lib/bootstrap-3.1.1-dist
- url: /
  static_files: ../client/templates/index.html
  upload: templates/index\.html
- url: /add_item
  static_files: ../client/templates/add_item.html
  upload: templates/add_item\.html
- url: /css
  static_dir: ../client/css
- url: /_ah/spi/.*
  script: secure_coding_api.APPLICATION

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0