application: sec-coding-2014
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler

- url: /_ah/spi/.*
  script: secure_coding_api.APPLICATION

#routing

#assets
- url: /js
  static_dir: ../client/js
- url: /bootstrap
  static_dir: ../client/lib/bootstrap-3.1.1-dist
- url: /css
  static_dir: ../client/css
- url: /lib
  static_dir: ../client/lib
#pages
- url: /
  static_files: ../client/index.html
  upload: index\.html
- url: /pages
  static_dir: ../client/pages

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0